"use client";

import Image from "next/image";
import { useState, useEffect } from "react";
import useRealProgress from "@/hooks/useRealProgress";
import Reveal from "@/components/Reveal";

export default function NeuroPortalsPage() {
  const loadingProgress = useRealProgress();
  const [showContent, setShowContent] = useState(false);

  useEffect(() => {
    if (loadingProgress >= 100) {
      const timer = setTimeout(() => setShowContent(true), 200);
      return () => clearTimeout(timer);
    }
  }, [loadingProgress]);

  return (
    <main className="min-h-screen bg-[#000021] text-white overflow-hidden">
      {showContent && (
        <div className="mx-auto max-w-6xl px-6 pb-24 pt-16 space-y-32">
          {/* SECTION 1 – Hero Intro */}
          <section className="grid gap-10 md:grid-cols-2 md:min-h-[80vh] md:items-center">
            <Reveal delay={0.40}>
              <div className="space-y-4">
                <p className="text-[10px] uppercase tracking-[0.3em] text-[#00A4FF]/70">
                  Interactive Installation
                </p>
                <h1 className="text-4xl md:text-5xl font-semibold tracking-wide">
                  NeuroPortals
                </h1>
                <h2 className="text-sm md:text-base text-white/70">
                  – Making Art With Your Brain –
                </h2>
                <p className="text-sm md:text-base leading-relaxed text-white/85">
                  Inspired by my Japanese cultural heritage and childhood memories, I wanted to create an interactive art installation that bridges tradition and modernity. What if the shoji paper windows could serve as a canvas to display mental states?
                </p>
                <p className="text-sm md:text-base leading-relaxed text-white/85">
                  By combining incense as an olfactory guide and EEG technology, my goal was to visualize brainwave patterns on shoji paper windows to create a dynamic and meditative ambiance.
                </p>
              </div>
            </Reveal>

            <Reveal delay={0.45}>
              <div className="relative h-[80vh]">
                <div className="relative overflow-hidden h-full">
                  <Image
                    src="/images/NeuroPortals/Image_vision.png"
                    alt="NeuroPortals Vision"
                    width={700}
                    height={400}
                    className="h-full w-full object-contain"
                    priority
                  />
                </div>
              </div>
            </Reveal>
          </section>

          {/* SECTION 2 – Collaboration & Muse */}
          <section className="grid gap-10 md:grid-cols-2 md:items-center">
            <Reveal delay={0.2}>
              <div className="overflow-hidden">
                <Image
                  src="/images/NeuroPortals/Muse-2.png"
                  alt="Muse 2 Headset"
                  width={900}
                  height={600}
                  className="h-full w-full object-cover"
                />
              </div>
            </Reveal>
            <Reveal>
              <div className="space-y-4 max-w-xl">
                <p className="text-[11px] uppercase tracking-[0.25em] text-white/50">
                  Technology
                </p>
                <h3 className="text-xl md:text-2xl font-semibold">
                  EEG Brainwave Sensing
                </h3>
                <p className="text-sm md:text-base leading-relaxed text-white/90">
                  This project was a collaboration with Fleuriane LAM, who primarily focused on promoting creativity through art.
                </p>
                <p className="text-sm md:text-base leading-relaxed text-white/90">
                  We used the <span className="text-[#00A4FF] font-medium">Muse 2 headset</span>, a commercial EEG device designed to track electrical signals generated by brain activity. This headset captures brainwave data, enabling real-time monitoring and analysis of mental states such as relaxation, focus, and mindfulness.
                </p>
              </div>
            </Reveal>
          </section>

          {/* SECTION 3 – Brainwave Processing */}
          <section className="grid gap-10 md:grid-cols-2 md:items-center">
            <Reveal>
              <div className="space-y-4">
                <p className="text-[11px] uppercase tracking-[0.25em] text-white/50">
                  Signal Processing
                </p>
                <h3 className="text-xl md:text-2xl font-semibold">
                  Five Brainwave Types
                </h3>
                <p className="text-sm md:text-base leading-relaxed text-white/90">
                  Using Python, we processed these signals and filtered them into five distinct brainwave types based on their frequency ranges:
                </p>
                <ul className="text-sm md:text-base leading-relaxed text-white/90 space-y-2">
                  <li>• <span className="text-[#00A4FF] font-medium">Delta</span> (0.5 - 4 Hz) - deep relaxation and sleep</li>
                  <li>• <span className="text-[#00A4FF] font-medium">Theta</span> (4 - 8 Hz) - creativity and meditation</li>
                  <li>• <span className="text-[#00A4FF] font-medium">Alpha</span> (8 - 12 Hz) - calmness and readiness</li>
                  <li>• <span className="text-[#00A4FF] font-medium">Beta</span> (12 - 30 Hz) - active thinking and focus</li>
                  <li>• <span className="text-[#00A4FF] font-medium">Gamma</span> (30 - 100 Hz) - cognitive functions</li>
                </ul>
              </div>
            </Reveal>

            <Reveal delay={0.1}>
              <div className="flex flex-col gap-4">
                <div className="overflow-hidden">
                  <Image
                    src="/images/NeuroPortals/Figure_2.png"
                    alt="Brainwave analysis graph 1"
                    width={300}
                    height={300}
                    className="h-full w-full object-contain"
                  />
                </div>
                <div className="overflow-hidden">
                  <Image
                    src="/images/NeuroPortals/Figure_1.png"
                    alt="Brainwave analysis graph 2"
                    width={300}
                    height={300}
                    className="h-full w-full object-contain"
                  />
                </div>
              </div>
            </Reveal>
          </section>

          {/* SECTION 4 – TouchDesigner & Real-time Visuals */}
          <section className="w-screen relative left-1/2 right-1/2 -ml-[50vw] -mr-[50vw]">
            <div className="px-6 py-16">
              <div className="mx-auto max-w-6xl space-y-8">
                <Reveal>
                  <div className="space-y-4">
                    <p className="text-[11px] uppercase tracking-[0.25em] text-white/50">
                      Real-time Graphics
                    </p>
                    <h3 className="text-xl md:text-2xl font-semibold">
                      TouchDesigner Integration
                    </h3>
                    <p className="text-sm md:text-base leading-relaxed text-white/90">
                      We sent the filtered data via Open Sound Control (OSC) on port 5000, which was received by <span className="text-[#00A4FF] font-medium">TouchDesigner</span> — a node-based visual programming software for real-time graphics and interactive media.
                    </p>
                    <p className="text-sm md:text-base leading-relaxed text-white/90">
                      This allowed us to create visuals that respond dynamically to the EEG sensor data, enabling real-time interaction and artistic expression.
                    </p>
                  </div>
                </Reveal>

                <Reveal delay={0.15}>
                  <div className="grid grid-cols-3 gap-4">
                    <div className="overflow-hidden">
                      <video autoPlay muted loop className="h-full w-full object-cover">
                        <source src="/images/NeuroPortals/Média1.mp4" type="video/mp4" />
                        Your browser does not support the video tag.
                      </video>
                    </div>
                    <div className="overflow-hidden">
                      <video autoPlay muted loop className="h-full w-full object-cover">
                        <source src="/images/NeuroPortals/Média2.mp4" type="video/mp4" />
                        Your browser does not support the video tag.
                      </video>
                    </div>
                    <div className="overflow-hidden">
                      <video autoPlay muted loop className="h-full w-full object-cover">
                        <source src="/images/NeuroPortals/Média3.mp4" type="video/mp4" />
                        Your browser does not support the video tag.
                      </video>
                    </div>
                  </div>
                </Reveal>
              </div>
            </div>
          </section>

          {/* SECTION 5 – Prototype & Testing */}
          <section className="grid gap-10 md:grid-cols-2 md:items-center">
            <Reveal>
                <div className="space-y-4">
                  <p className="text-[11px] uppercase tracking-[0.25em] text-white/50">
                    Development
                  </p>
                  <h3 className="text-xl md:text-2xl font-semibold">
                    Prototype & Projection Mapping
                  </h3>
                  <p className="text-sm md:text-base leading-relaxed text-white/90">
                    We first tested visuals in TouchDesigner, exploring how brainwave and heartbeat data could drive generative patterns. Once we had those first visuals, we built a small-scale model of the doors and tried projection mapping.
                  </p>
                  <p className="text-sm md:text-base leading-relaxed text-white/90">
                    This helped us visualize how the patterns could come to life on a three-dimensional surface and guided us as we moved toward the final installation.
                  </p>
                </div>
              </Reveal>

              <Reveal delay={0.1}>
                <div className="flex flex-col gap-4">
                  <div className="overflow-hidden">
                    <Image
                      src="/images/NeuroPortals/proto.png"
                      alt="Prototype model"
                      width={300}
                      height={300}
                      className="h-full w-full object-cover"
                    />
                  </div>
                  <div className="overflow-hidden">
                    <video autoPlay muted loop className="h-full w-full object-cover">
                      <source src="/images/NeuroPortals/proto.MP4" type="video/mp4" />
                      Your browser does not support the video tag.
                    </video>
                  </div>
                </div>
              </Reveal>
          </section>

          {/* SECTION 6 – Final Installation */}
          <section className="grid gap-10 md:grid-cols-2 md:items-center">
            <Reveal delay={0.15}>
              <div className="grid grid-cols-2 gap-4">
                <div className="overflow-hidden h-[300px]">
                  <Image
                    src="/images/NeuroPortals/fab1.JPG"
                    alt="Door fabrication 1"
                    width={300}
                    height={300}
                    className="h-full w-full object-cover"
                  />
                </div>
                <div className="overflow-hidden h-[300px]">
                  <Image
                    src="/images/NeuroPortals/fab2.JPG"
                    alt="Door fabrication 2"
                    width={300}
                    height={300}
                    className="h-full w-full object-cover"
                  />
                </div>
              </div>
            </Reveal>
            <Reveal>
              <div className="space-y-4 max-w-xl">
                <p className="text-[11px] uppercase tracking-[0.25em] text-white/50">
                  Final Installation
                </p>
                <h3 className="text-xl md:text-2xl font-semibold">
                  Building the Shoji Doors
                </h3>
                <p className="text-sm md:text-base leading-relaxed text-white/90">
                  For the final installation, we built a larger model of our "doors"—the architectural structure that housed the projections. This made the experience more immersive and deepened the installation's meditative quality.
                </p>
                <p className="text-sm md:text-base leading-relaxed text-white/90">
                  Since we didn't have actual shoji windows, we made our own shoji-style doors using wooden battens, wood strips, and calligraphy paper. Each brainwave type was connected to a different color and pattern, with heartbeat data controlling the speed of the animations.
                </p>
              </div>
            </Reveal>
          </section>

          {/* SECTION 7 – Final Performance */}
          <section className="space-y-8 md:space-y-10">
            <Reveal>
              <div className="text-center space-y-3">
                <h3 className="text-xl md:text-2xl font-semibold">
                  Dance & Projection Performance
                </h3>
              </div>
            </Reveal>

            <Reveal delay={0.15}>
              <p className="mx-auto text-sm md:text-base leading-relaxed text-white/85">
                Finally, after completing the doors we did projection mapping to display the animations controlled by the brainwaves. Not only could we visualize the brain activity, but we also played with shadows through collaboration with amazing dancers, creating a truly immersive and multisensory experience.
              </p>
            </Reveal>

            <Reveal delay={0.1}>
              <div className="grid grid-cols-4 gap-4">
                <div className="overflow-hidden h-[400px]">
                  <Image
                    src="/images/NeuroPortals/final_porte1.jpg"
                    alt="Final installation 1"
                    width={400}
                    height={400}
                    className="h-full w-full object-cover"
                  />
                </div>
                <div className="overflow-hidden h-[400px]">
                  <video autoPlay muted loop className="h-full w-full object-cover">
                    <source src="/images/NeuroPortals/dance.mp4" type="video/mp4" />
                    Your browser does not support the video tag.
                  </video>
                </div>
                <div className="overflow-hidden h-[400px]">
                  <Image
                    src="/images/NeuroPortals/final_porte2.JPG"
                    alt="Final installation 2"
                    width={400}
                    height={400}
                    className="h-full w-full object-cover"
                  />
                </div>
                <div className="overflow-hidden h-[400px]">
                  <video autoPlay muted loop className="h-full w-full object-cover">
                    <source src="/images/NeuroPortals/violet.mp4" type="video/mp4" />
                    Your browser does not support the video tag.
                  </video>
                </div>
              </div>
            </Reveal>
          </section>
        </div>
      )}
    </main>
  );
}
